// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9f3ppuFxPsLjsCyjOxy4_5-O_SQ7Pfco',
    appId: '1:967683675898:web:4ee5f089b251523965db43',
    messagingSenderId: '967683675898',
    projectId: 'alias-pro-a8ddc',
    authDomain: 'alias-pro-a8ddc.firebaseapp.com',
    storageBucket: 'alias-pro-a8ddc.firebasestorage.app',
    measurementId: 'G-QXM6C8LR7P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvkVbN8buPEY1PZIRq28p6OgcJgIQdRU0',
    appId: '1:967683675898:android:698451521831a14965db43',
    messagingSenderId: '967683675898',
    projectId: 'alias-pro-a8ddc',
    storageBucket: 'alias-pro-a8ddc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZOlgKL74heMpk2KZv5rCqVR2P6W6Okss',
    appId: '1:967683675898:ios:bf5f4c6da78bd9ed65db43',
    messagingSenderId: '967683675898',
    projectId: 'alias-pro-a8ddc',
    storageBucket: 'alias-pro-a8ddc.firebasestorage.app',
    iosBundleId: 'com.example.aliasPro',
  );
}
